# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 16:23
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=None, default_currency='BRL', max_digits=8, null=True, verbose_name='Price'),
        ),
    ]
